name: Release

on:
  push:
    tags: [v*]

# Automatically cancel older in-progress jobs on the same ref
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  release-notes:
    name: Generate release notes
    runs-on: ubuntu-24.04

    outputs:
      release-notes: ${{ steps.release-notes.outputs.body }}

    timeout-minutes: 30
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Install git-cliff
        run: |
          VERSION="2.10.1"
          cd "${RUNNER_TEMP}"
          wget "https://github.com/orhun/git-cliff/releases/download/v${VERSION}/git-cliff-${VERSION}-x86_64-unknown-linux-gnu.tar.gz"
          tar -xvzf git-cliff-${VERSION}-x86_64-unknown-linux-gnu.tar.gz
          sudo mv git-cliff-${VERSION}/git-cliff /usr/local/bin/
          git-cliff --version

      - name: Generate release notes
        id: release-notes
        run: |
          git-cliff -v -c cliff.config.toml --strip all --output release-notes.md --current
          cat release-notes.md

          {
            echo 'body<<EOF'
            cat release-notes.md
            echo EOF
          } >> $GITHUB_OUTPUT

  release:
    name: Release
    runs-on: ubuntu-24.04
    needs: [release-notes]

    timeout-minutes: 60
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version-file: go.mod

      - name: Prepare release notes template
        run: |
          cat > "${RUNNER_TEMP}/release-notes.md" <<'EOF'
          ${{ needs.release-notes.outputs.release-notes }}
          EOF
          cat "${RUNNER_TEMP}/release-notes.md"

      - name: Validate module dependencies
        run: go mod tidy

      - name: Run GoReleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # v6.4.0
        with:
          version: '~> v2'
          args: release --verbose --clean --draft --release-notes "${RUNNER_TEMP}/release-notes.md"
